[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "preprocess-utils"
version = "0.1.1"
authors = [
    {name = "ctilab-jho", email = "jho@ctilab.co.kr"}
]
dependencies = [
    "tensorflow==2.10.0",
]
requires-python = ">=3.8"